name: .env
channels:
  - defaults
dependencies:
  - python=3.10  # lowest version allowed by mypy

  - numpy

  # Linting
  - pre-commit
  - pytest
  - black
  - flake8
  - mypy

  # Tests
  - pytest
