name: Edugrad CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        repository: 'tostenzel/edugrad'
        ref: 'main'

    - name: Setup Conda Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: '.env'
        environment-file: 'environment.yaml'
        auto-activate-base: false

    - name: Install Edugrad
      run: |
        pip install -e .

    - name: Run Tests
      run: |
        conda activate .env
        conda list
        pytest tests
